package com.devops.dxc.devops;
// Generated by Selenium IDE
import org.junit.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;


public class Tramo3Caso2Test {
  private WebDriver driver;  
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.out.println("Iniciando configuración...");
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver.exe");
    driver = new ChromeDriver();    
  }
  @Test
  public void tramo3Caso2() {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(820, 725));
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("9000000");
    {
      WebElement element = driver.findElement(By.cssSelector(".boton_form"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("1600000");
    driver.findElement(By.cssSelector(".boton_form")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    String diezXC;
    String saldoPost;
    String impuesto;
    {
      WebDriverWait wait = new WebDriverWait(driver, 2);
      wait.until(ExpectedConditions.textToBe(By.id("resutl_10xc"), "$600,000"));
      wait.until(ExpectedConditions.textToBe(By.id("result_saldo_post"), "$600,000"));
      wait.until(ExpectedConditions.textToBe(By.id("result_impuesto"), "$600,000"));
    }
    
    diezXC = driver.findElement(By.id("result_10xc")).getText();    
    saldoPost = driver.findElement(By.id("result_saldo_post")).getText();    
    impuesto = driver.findElement(By.id("result_impuesto")).getText();    
    assertEquals("$600,000", diezXC);
    assertEquals("$600,000", saldoPost);
    assertEquals("$600,000", impuesto);
  }
}
