package com.devops.dxc.devops;
// Generated by Selenium IDE
import org.junit.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.Before;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;


public class Tramo1Caso1Test {
  private WebDriver driver;  
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.out.println("Iniciando configuración...");
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver.exe");
    driver = new ChromeDriver();    
  }
  
  @Test
  public void tramo1Caso1() {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(820, 725));
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("600000");    
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("mat-input-1")).sendKeys("1200000");
    driver.findElement(By.cssSelector(".mat-button-wrapper")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }

    String diezXC;
    {
      WebDriverWait wait = new WebDriverWait(driver, 2);
      wait.until(ExpectedConditions.textToBe(By.id("resutl_10xc"), "$600,000"));      
    }
    
    diezXC = driver.findElement(By.id("result_10xc")).getText();    
    assertEquals("$600,000", diezXC);

    
  }
}
